export const cardsData = [
  {
    uid: '1',
    photoUrl: '/avatars/girl.jpg',
    title: "Ce n'est qu'un aurevoir",
    creationDate: "24 janvier 2021",
    recipientName: "Marc Dubois",
    messageNumber: 14,
    money: 254,
    url:'https://omerci.com/cardId=1',
    isSent: false,
  },
  {
    uid: '2',
    photoUrl: '/avatars/girl.jpg',
    title: "Prochaine aventure",
    creationDate: "2 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=2',
    isSent: false,
  },
  {
    uid: '3',
    photoUrl: '/avatars/girl.jpg',
    title: "Prochaine aventure sent",
    creationDate: "21 février 2023",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=3',
    isSent: true,
  },  {
    uid: '4',
    photoUrl: '/avatars/girl.jpg',
    title: "Prochaine aventure sent",
    creationDate: "21 février 2024",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=4',
    isSent: true,
  }, 
  {
    uid: '5',
    photoUrl: '/avatars/girl.jpg',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=5',
    isSent: false,
  },  {
    uid: '6',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=6',
    isSent: false,
  },  {
    uid: '7',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=7',
    isSent: false,
  },  {
    uid: '25',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=25',
    isSent: false,
  },  {
    uid: '47',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=47',
    isSent: false,
  },  {
    uid: '8',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=8',
    isSent: false,
  },  {
    uid: '9',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=9',
    isSent: false,
  },  {
    uid: '10',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=10',
    isSent: false,
  },  {
    uid: '11',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=11',
    isSent: false,
  },  {
    uid: '12',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=12',
    isSent: false,
  },  {
    uid: '13',
    photoUrl: '',
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url:'https://omerci.com/cardId=13',
    isSent: false,
  },
]