export const cardsData = [
  {
    photoUrl: "string",
    title: "Ce n'est qu'un aurevoir",
    creationDate: "24 janvier 2021",
    recipientName: "Marc Dubois",
    messageNumber: 14,
    money: 254,
    url: "YVens",
    isSent: false,
  },
  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "2 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Fadel",
    isSent: false,
  },
  {
    photoUrl: "string",
    title: "Prochaine aventure sent",
    creationDate: "21 février 2023",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "bartra",
    isSent: true,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure sent",
    creationDate: "21 février 2024",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: true,
  }, 
  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },  {
    photoUrl: "string",
    title: "Prochaine aventure",
    creationDate: "21 février 2022",
    recipientName: "Marc Dubois",
    messageNumber: 52,
    money: 1200,
    url: "Bye",
    isSent: false,
  },
]