import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/buttons/Button';
import BrandIcon from '../public/icons/Alarm.svg'

const Home: NextPage = () => {
  return (
    <div className='flex justify-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button myClass={'bg-primary text-white'} handleClick={() => console.log('hi')}>
        <>
          <BrandIcon className='fill-white mr-2'/>
          <span className=''>Delete</span>
        </>
      </Button>
    </div>
  )
}

export default Home
